export const CONSTANTS = {
    LOGIN_HEADING: 'Welcome to Logistics Orchestration',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    USERNAME_EMPTY_MESSGAE: 'Username is required',
    PASSWORD_EMPTY_MESSGAE: 'Password is required',
    FORGOT_USERNAME: 'Forgot Username',
    FORGOT_PASSWORD: 'Forgot Password',
    INVALID_USERNAME_PASSWORD_MESSAGE: 'Invalid Username or Password',
    LOGIN: 'Login',
    LOGIN_WITH_SSO: 'Login with SSO',
    PREVIOUS:'Previous Vehicle',
    PREVIOUS_VEHICLE:'Previous Vehicle',
    CURRENT_VEHICLE:'Current Vehicle',
    EXPECTED_COMPLETION:'Expected Completion',
    EXPECTED_INSTALL_TIME:'Expected Install Time',
    DROP_OFF_LOCATION:'Drop Off Location',
    PICK_UP_LOCATION:'Pick Up Location',
    NEXT_VEHICLE:'Next Vehicle',
    PLANNED_START_TIME:'Planned Start Time',
    NEXT_VEHICLE_IS_NOT_AVAILABLE:'Please contact your supervisor to get information about next VIN',
    SHOP:'Shop',
    CODE:'Code',
    ACCESSORY_DESCRIPTION:'Accessory Description',
    ACCESSORY_PART_NUMBER:'Accessory Part Number(s)',
    EXP_TIME:'Exp. Time',
    INSTALLED:'Installed',
    NOT_INSTALLED:'Not Installed',
    SUBMIT: "Submit",
    CURRENT_VEHICLE_INSTALLATION:'Current Vehicle Installation',
    SCAN_NEXT_VIN:'Scan Next VIN',
    VIN_ID_EMPTY_MESSAGE:'VIN is required',
    ENTER_VIN:'Enter VIN',
    NOT_INSTALLED_REASON:'Not Installed Reason',
    CANCEL: "Cancel",
    CONFIRM: "CONFIRM",
    VEHICLES:'Vehicles',
    HOURS:'Hours',
    TEAM_MEMBER_AT_STALL:'Team Member(s) at Stall',
    STALL_PROGRESS_CURRENT_SHIFT:'Stall Progress - Current Shift ',
    SHOP_PROGRESS_CURRENT_SHIFT:'Shop Progress - Current Shift',
    PLANNED:'Planned',
    VEHICLE_SUCCESS_MESSAGE:'Vehicle accessory installations was successfully completed',
    VIN_ID_INVALID_MESSAGE1:'Warning - Inventory Code',
    VIN_ID_INVALID_MESSAGE2:"This vehicle's inventory code is",
    VIN_ID_INVALID_MESSAGE3:'Choose to continue installation or scan another VIN',
    YES_CANCEL_CURRENT_VIN: "Yes cancel current VIN",
    NO_BACK_TO_CUURENT_VIN: "No back to current VIN",
    CANCEL_MODAL_HEADER: "Are you sure you want to cancel ?",
    CONFIRM_MODAL_CONTENT: "Please confirm you want to cancel the current VIN without submitting progress",
    TABLE_SUBMIT_MODAL_HEADER: "Do you want to submit vehicle accessory installations?",
    TABLE_SUBMIT_MODAL_CONTENT: `You have initialized submission of accessory installations for the vehicle at this stall.
    Click Cancel to return to Current Vehicle Installation. Use Confirm to
    finalize submission.`,
    MANAGER_SITE_METRIC_SHOP_FLOOR_HEADER: "Today’s Progress across Site",
    MANAGER_SITE_METRIC_SHOP_FLOOR_SUB_HEADER: "Hover on a shop for additional metrics."
};